### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by jibiel** [louis-kevin/vcr#2]
Is there any plans to migrate the package to null safety?

`vcr` is currently complicates migration to null safety for the apps that depend on it.

The easiest way to do this would be to:

- [ ] Update `Dio` to `dio: ^4.0.0`. It also has some new API (like `interpceptor` `handler`s), but it should be trivial to update to.
- [ ] Switch from `mockito` to [`mocktail`](https://pub.dev/packages/mocktail). `mockito` is currently one of the biggest dependencies that block migration to null safety without significant rewrites. It is now basically offers either manually defined mocks or code generation: https://github.com/dart-lang/mockito/issues/286. `mocktail` allows a migration of a `mockito` code to null safety with minimal rewrites as their APIs are almost identical. There is also a discussion about merging `mocktail` into `mockito`: https://github.com/dart-lang/mockito/issues/347.

There is also a PR that solves the issue by completely dropping the `mockito` dependency: https://github.com/keviinlouis/vcr/pull/1.

So, how should we go about this?

**Comment by alex-min** [comment]
I don't think mockito is necessary, the package is small and just overriding the methods works.

I'm currently using my null saferty fork of vcr in my project, in the mean time the PR is merged you can replace vcr in the pubspec file by my fork:

 ```
  vcr:
    git:
      url: https://github.com/alex-min/vcr.git
      ref: de33eec6831be95b4e55eac4f661c6e3d0df3822
```

**Comment by jibiel** [comment]
@keviinlouis Any input on that?

**Comment by alex-min** [comment]
To people reading this, I've published the forked package with null safety https://pub.dev/packages/vcr2/, I'm going to maintain it forward, I need it for my project.

**Comment by louis-kevin** [comment]
Hello There, sorry about the longest delay ever, but I added null safe and refactor a bit, if you guys are using this package yet, plz check if works for you!

Thanks!

**Comment by louis-kevin** [comment]
cc @alex-min @jibiel
